version: '3.8'

networks:
    docker:

services:

    jenkins:
        image: jenkins/jenkins:lts #or use jenkins/jenkins:jdk17-preview if failing to install
        restart: always
        networks:
            - docker
        ports:
            - "8081:8080"
            - "50000:50000"
        container_name: jenkins
        volumes:
            - ./jenkins_data:/var/jenkins_home

    jenkins_proxy:
        restart: always
        image: nginx
        networks:
            - docker
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './nginx/error_logs:/etc/nginx/error_logs'
            # - './nginx/certs:/etc/nginx/certs'
        ports:
            - "80:80"
            # - "443:443"
        depends_on:
            - jenkins
                
